### ISSUE TITLE
Question - How does this differ from ResponseCaching? 

### ISSUE THREAD

**Issue by awright18** [madskristensen/WebEssentials.AspNetCore.OutputCaching#15]
What about https://github.com/aspnet/AspNetCore/tree/master/src/Middleware/ResponseCaching
From what I've read they want to make this a bit more configurable.  Is there a reason I might want to use your output caching instead of ResponseCaching?

**Comment by jodydonetti** [comment]
ResponseCaching set some HTTP headers, telling proxies/clients how they should cache the response.

This instead, on top of doing the same thing, also caches the response in the server (memory) itself, so that even if clients force-request the page on the server bypassing HTTP cache-related headers or if other clients will make the same request, the server will not re-process the request again, instead giving immediately the same response already cached before.

Hope @madskristensen agrees with this explanation 😅

**Comment by jodydonetti** [comment]
@madskristensen if you are into spring cleaning I think this can be closed.
